export const ASSIGNMENT_STATUS = Object.freeze({
    PENDIENTE: 'PENDIENTE',
    EN_PROCESO: 'EN_PROCESO',
    ENVIADO: 'ENVIADO',
    EN_REVISION: 'EN_REVISION',
    COMPLETADO: 'COMPLETADO'
});

export const SYSTEM_ROLES = Object.freeze({
    ESTUDIANTE: 'ESTUDIANTE',
});